### ISSUE TITLE
Kore Features To Eliminate/Simplify

### ISSUE THREAD

**Issue by IljaZakharov** [Pi-Squared-Network/pi2#757]
This is a high-level issue for ongoing discussions regarding a couple of Kore feature that the proof generation team would like to eliminate/simplify in Kore. Potentially we might want to discuss them all with the K team to discuss potential solutions.

Guiding Principles
===============

### Principle 1: Do not make changes purely for the sake of improving Kore.

It is important to remember that Kore has been deployed as is already in use by the various backends. It takes coordination and effort to change things. We should make changes only if it improves the lives of some consumer of Kore.  At the same time, we should make notes about the general direction we want to  move in.

### Principle 2:  Prefer  abstraction over precise matching logic definitions

The Kore language is intended to communicate between the frontend, backends, and various other tools the language semantics defined in a K definition in a succinct way. As such, it should not get bogged down by the details of matching logic. This unnecessarily forces users to reconstruct information. 
Matching logic supports notations. We should use these to allow abstraction. 

Concrete Issues
=============

Subsorting and Injections
--------------------------------------

The `definition.kore` file defines that `Int` is a subsort of `Tree` with the following axiom:

```
  axiom{R} \exists{R} (Val:SortTree{}, \equals{SortTree{}, R} (Val:SortTree{}, inj{SortInt{}, SortTree{}} (From:SortInt{}))) [subsort{SortInt{}, SortTree{}}()] // subsort
```

This axiom is quite vague, merely saying that `inj{Int, Tree}` is a function from `Int` to `Tree`.
I doubt that any backend  would find it useful to parse this axiom, and is likely just using the attribute.
In general, `inj` is quite underspecified. There are no axioms stating that if `Foo` is *not* a subsort of `Bar`, then `inj{Bar, Foo}` is bottom. In Matching Logic models,  `inj` may be an arbitrary function or partial function, or really many other arbitrary relations.

@nishantjr proposes we replace this with:

```
axiom{R} subsort{R, SortInt{}, SortTree{}}() [subsort{SortInt{}, SortTree{}}()]
```

Here,
*  `subsort{R, SortInt{}, SortTree{}}()` is documented to be matching logic notation for `subset{R} (Top{SortInt{}}, Top{SortTree{}})`.
* `inj{InnerSort{}, OuterSort}(t)` is documented to be notation for `t /\ Top{SortOuter}`. Note that this is the general matching logic `/\` and not Kore `and`, since `t` and  `Top{SortOuter}` have distinct sorts. We may also chose to drop `inj` entirely or define `inj{InnerSort{}, OuterSort}(t)` as notation for simply `t`.

Let bindings
------------------

 The recent version of K introduces substitutions for some of the let bindings, and we would also like to have an explicit let binding in Kore.

Substitutions.
* Base substitutions shouldn't be a part of rewrite substitutions for rule applications.
* Substitutions should ideally not contain element variables, if they have to, they should go before rewrite substitutions and the hint should provide a list of contained element variables substitutions.

Outer sorts (Possibly controversial). Could we get rid of the outer sorts? Now, since they can be picked, the problematic thing is that we have to wrap every claim with `claim = Top_{outer_sort}`. It would be much easier to simply prove `claim`. 

## Substitututions

We have a simple K definition for testing simplifications:
```
module TREE-REVERSE-INT-SYNTAX

    imports DOMAINS-SYNTAX

    syntax Tree ::= node(Tree, Tree) | Int
    syntax Tree ::= reverse(Tree) [function, total]
    syntax KItem ::= "#Init"
    syntax KItem ::= "#next"

endmodule

module TREE-REVERSE-INT

    imports DOMAINS
    imports TREE-REVERSE-INT-SYNTAX

    rule [base-case] : reverse(X:Int) => X
    rule [rec-case] :  reverse(node(T1, T2)) => node(reverse(T2), reverse(T1))
    rule [init] : <k> #Init => #next </k>
    rule [next] : <k> #next => reverse(node(1:Int, 5:Int)) </k>

endmodule
```

The `base-case` rule is translated to Kore with let bindings like this:
```
  axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortTree{}, R} (
            X0:SortTree{},
            \and{SortTree{}}(inj{SortInt{}, SortTree{}}(VarX:SortInt{}),Var'Unds'Gen0:SortTree{})
          ),
          \top{R} ()
        )),
    \equals{SortTree{},R} (
      Lblreverse'LParUndsRParUnds'TREE-REVERSE-INT-SYNTAX'Unds'Tree'Unds'Tree{}(X0:SortTree{}),
     \and{SortTree{}} (
       Var'Unds'Gen0:SortTree{},
        \top{SortTree{}}())))
  [UNIQUE'Unds'ID{}("7caac86bcc560c5dcd41b8f2a2281385a1bc6308bfe4d29984cc50a21c4d695c"), label{}("TREE-REVERSE-INT.base-case"), org'Stop'kframework'Stop'attributes'Stop'Location{}("Location(17,24,17,43)"), org'Stop'kframework'Stop'attributes'Stop'Source{}("Source(/Users/zakharov/src/proof-checker/generation/k-benchmarks/tree-reverse-int/tree-reverse-int.k)"), org'Stop'kframework'Stop'definition'Stop'Production{}("syntax #RuleContent ::= #RuleBody [klabel(#ruleNoConditions), symbol]")]
```

We need to derive an equation from this form without the let binding and with all its free variables universally quantified. In order to do so, we apply so called-base substitutions to remove additionally introduced element variables by substituting `Var'Unds'Gen0` and `VarX`.

Hints contain the following substitutions (in the pretty-printing format): 
`VarX`: 'dv(5):ksort_SortInt'
`Var'Unds'Gen0`: `inj(ksort_SortInt, ksort_SortTree, dv(5):ksort_SortInt)`

**The problem** here is that we need to know how exactly K backend generates hints for let bindings so we can support all cases appropriately and apply only those base substitutions that won't be provided by K in hints. We can't rely only on hints also because there are some cases when K misses some of substitutions. The example is below in a comment.

**Comment by IljaZakharov** [comment]
There is another example without sort injections:

```
module TREE-REVERSE-SYNTAX

    syntax Tree ::= "a" | "b" | "c" | node(Tree, Tree)
    syntax Tree ::= reverse(Tree) [function, total]
    syntax KItem ::= "#Init"
    syntax KItem ::= "#next"

endmodule

module TREE-REVERSE

    imports TREE-REVERSE-SYNTAX

    rule [base-case-a] : reverse(a) => a
    rule [base-case-b] : reverse(b) => b
    rule [base-case-c] : reverse(c) => c
    rule [rec-case] :  reverse(node(T1, T2)) => node(reverse(T2), reverse(T1))
    rule [init] : <k> #Init => #next </k>
    rule [next] : <k> #next => reverse(node(a, b)) </k>

endmodule
```

The rule:
```
axiom{R} \implies{R} (
    \and{R}(
      \top{R}(),
      \and{R} (
          \in{SortTree{}, R} (
            X0:SortTree{},
            \and{SortTree{}}(Lbla'Unds'TREE-REVERSE-SYNTAX'Unds'Tree{}(),Var'Unds'Gen0:SortTree{})
          ),
          \top{R} ()
        )),
    \equals{SortTree{},R} (
      Lblreverse'LParUndsRParUnds'TREE-REVERSE-SYNTAX'Unds'Tree'Unds'Tree{}(X0:SortTree{}),
     \and{SortTree{}} (
       Var'Unds'Gen0:SortTree{},
        \top{SortTree{}}())))
```

K doesn't generate substitutions for let bindings in hints, so we need to figure them out ourself anyway.

**Comment by Baltoli** [comment]
> We can't rely only on hints also because there are some cases when K misses some of substitutions.

I don't quite follow this - can you expand on what's _missing_ that you expect to see in this example?

> ... let bindings ...

Could you also define precisely which bits of the axiom declarations above you mean by let bindings? Just want to make sure we're looking at the same things.

**Comment by fiedlr** [comment]
@Baltoli 

1. The audit would be helpful, but I feel like it is not critical, we can discuss it in the technical meeting. 
2. I had a chat with @IljaZakharov and there was a misunderstanding. I also do not see any missing substitutions there. Basically any variable on the RHS of a let binding will occur in a substitution.

3. Let me try to clarify in a pseudosyntax. 

* Let bindings*
Consider the following formula:

`x in phi  -> reverse(x) = psi` 

Then `x in phi` is a let binding, because our current experience is that usually we only get formulas that are equivalent to

`x = phi  -> reverse(x) = psi` 

and so to

`reverse(phi) = psi`

We would love  to specify how let bindings are introduced, when, and with what `phi`'s. The first example shows that built-ins introduce more variables for built-in types.

*Base substitutions*

Let's take the second @IljaZakharov 's example, i.e., `phi = a /\ Gen0` and `psi = Gen0`.

A base substitution is such that resolves the let binding, i.e., in the above example, substituting for all the free variables , which is just `Gen0 |-> a`, yielding

``x in a /\ a  -> reverse(x) = a`

What we want to do, is simply save the more convenient `reverse(a) = a` and prove that it is equivalent to the original axiom, avoiding to reprove this all the time.  

*Rewrite substitutions*

Rewrite substitutions are those that instantiate the actual K rule given by `f(phi) = psi`. In the example above, the rewrite substitution would be empty. 

If we had a more involved example like the rec-case, rewrite substitutions are those instantiating `T1, T2` (as given by K semantics), and base substitutions are those substituting for variables  introduced by the let binding.

**Comment by xc93** [comment]
I just wanna say here that I totally agree with the two guiding principles. 

One comment on injections:
There should be an axiom in definition.kore that (wrongly) states that there exists an injection symbol inj{s1,s2} for any s1 and s2, and inj{s1,s2} is an injective function from s1 to s2. And this axiom is wrong because not every two sorts allow the existence of such an injective function, leading to inconsistency, but that's a separate issue to be addressed.

**Comment by fiedlr** [comment]
Conclusions

There is a confusion between a) base substitutions providing values for the auxiliary variables (like in this issue `VarX` and `Gen0`) and b) base substitutions in the code that simply map the let-bound variables (like `X0`). 

These are two different things and there's no issue in the proof hint format.

a) is part of hints and will remain so
b) will stay in the code to remove let bindings

To simplify the used axioms, what we will do is we will: 

1. Remove let bindings as given by the b) substitutions
2. Universally quantify the remaining axiom, that possibly contains a) substitutions
